#!/usr/bin/env node
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const INCLUDES_DIR = path.join(ROOT, "_includes");
const PAGES_DIR = path.join(ROOT, "src", "pages");
const SPRITES_DIR = path.join(ROOT, "sprites");
const SHARP_SPRITES = [
  "sharp-solid.svg",
  "sharp-regular.svg",
  "sharp-light.svg",
  "sharp-thin.svg",
];

const DEFAULTS = {
  title: "Giant Leap Foundation",
  current: "",
  description: "",
  keywords: "",
  ogTitle: "Giant Leap Foundation",
  ogDescription: "Giant Leap Foundation",
  ogUrl: "",
  ogImage: "",
  output: "index.html",
  robots: "",
};

const NAV_ITEMS = ["home", "curriculum", "content", "symposia", "about", "help"];

function readInclude(name) {
  return fs.readFileSync(path.join(INCLUDES_DIR, name), "utf8");
}

function ensureSprites() {
  for (const file of SHARP_SPRITES) {
    const spritePath = path.join(SPRITES_DIR, file);

    if (!fs.existsSync(spritePath)) {
      console.error(`Missing sprite: ${spritePath}`);
      process.exit(1);
    }
  }
}

function parsePage(source) {
  const meta = { ...DEFAULTS };
  const metaPattern = /^<!--\s*build:(\w+)\s+(.*?)\s*-->\s*$/gm;

  for (const match of source.matchAll(metaPattern)) {
    meta[match[1]] = match[2];
  }

  const content = source.replace(metaPattern, "").trim();
  return { meta, content };
}

function applyVars(template, vars) {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => vars[key] ?? "");
}

function extraHeadMeta(meta) {
  const tags = [];

  if (meta.robots) {
    tags.push(`<meta name="robots" content="${meta.robots}" />`);
    tags.push(`<meta name="googlebot" content="${meta.robots}" />`);
  }

  return tags.join("\n    ");
}

function buildIconManifest() {
  const weights = Object.fromEntries(
    SHARP_SPRITES.map((file) => [file.replace(".svg", ""), `sprites/${file}`]),
  );
  const viewBoxesByWeight = Object.fromEntries(
    SHARP_SPRITES.map((file) => {
      const source = fs.readFileSync(path.join(SPRITES_DIR, file), "utf8");
      const viewBoxes = {};

      for (const match of source.matchAll(/symbol id="([^"]+)" viewBox="([^"]+)"/g)) {
        viewBoxes[match[1]] = match[2];
      }

      return [file.replace(".svg", ""), viewBoxes];
    }),
  );
  const iconIds = Object.keys(viewBoxesByWeight["sharp-solid"]).sort();
  const icons = iconIds.map((id) => ({
    id,
    viewBoxes: Object.fromEntries(
      Object.entries(viewBoxesByWeight).map(([weight, viewBoxes]) => [weight, viewBoxes[id]]),
    ),
  }));

  fs.writeFileSync(
    path.join(ROOT, "icons.json"),
    JSON.stringify({ weights, icons }, null, 0),
  );
}

function navVars(current) {
  return Object.fromEntries(
    NAV_ITEMS.map((item) => [`nav_${item}`, current === item ? "nav active" : "nav"]),
  );
}

function buildPage(filePath) {
  const source = fs.readFileSync(filePath, "utf8");
  const { meta, content } = parsePage(source);
  const vars = {
    ...meta,
    ...navVars(meta.current),
    extraHead: extraHeadMeta(meta),
  };

  const html = [
    "<!-- Generated by `npm run build`. Edit src/pages/ instead. -->",
    applyVars(readInclude("head.html"), vars),
    readInclude("icon-sprites.html"),
    applyVars(readInclude("header.html"), vars),
    content,
    applyVars(readInclude("footer.html"), vars),
    readInclude("page-end.html"),
  ].join("\n");

  const outPath = path.join(ROOT, meta.output);
  fs.writeFileSync(outPath, html);
  return meta.output;
}

function main() {
  ensureSprites();
  buildIconManifest();

  if (!fs.existsSync(PAGES_DIR)) {
    console.error("Missing src/pages directory.");
    process.exit(1);
  }

  const pages = fs
    .readdirSync(PAGES_DIR)
    .filter((file) => file.endsWith(".html"))
    .map((file) => path.join(PAGES_DIR, file));

  if (pages.length === 0) {
    console.error("No pages found in src/pages.");
    process.exit(1);
  }

  for (const pagePath of pages) {
    const output = buildPage(pagePath);
    console.log(`Built ${output}`);
  }
}

main();
